version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg-orb: circleci/cimg-orb@dev:alpha

workflows:
  main:
    jobs:
      - build:
          context: cimg-publishing

jobs:
  build:
    executor: default
    steps:
      - cimg-orb/build-and-deploy:
          parameters:
            run-script: 'build-images.sh check-versions.sh'
            image: node
