version: 2.1

orbs:
  cimg: circleci/cimg@0.6.2
  slack: circleci/slack@4.12.1

parameters:
  cron:
    type: boolean
    default: false

workflows:
  automated-wf:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/update:
          update-script: nodeFeed.sh
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cpe-image-bot-github-creds
  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          resource-class: xlarge
          docker-namespace: ccitest
          docker-repository: node
          filters:
            branches:
              ignore:
                - main
          context: 
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
      - cimg/build-and-deploy:
          name: "Deploy"
          resource-class: xlarge
          docker-repository: node
          filters:
            branches:
              only:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
            - cimg-docker-image-publishing
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
      - push-alias-tags:
          filters:
            branches:
              only:
                - main
          requires:
            - Deploy
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
            - cimg-docker-image-publishing

jobs:
  push-alias-tags:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Log in to Docker"
          command: |
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: "Push aliased tags if release"
          command: |
            if git log -1 --pretty=%s | grep "\[release\]"; then
              git diff --quiet HEAD~1 ALIASES || ./push-images.sh
            fi
