version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg: circleci/cimg@dev:27ea434821b7bcf2dc5d35ad412236e439ed00f2

workflows:
  main:
    jobs:
      - cimg/gen-dockerfiles
      - cimg/build-and-deploy:
          name: "Push to Staging"
          publish-branch: test
          docker-namespace: ccitest
          docker-repository: node
          context: cimg-publishing
          requires:
            - cimg/gen-dockerfiles
      - cimg/build-and-deploy:
          name: "Push to Production"
          publish-branch: main
          docker-namespace: cimg
          docker-repository: node
          context: cimg-publishing
          requires:
            - "Push to Staging"
          filters:
            branches:
              only: main
