version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg-orb: circleci/cimg-orb@dev:alpha

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - cimg-orb/build-and-deploy:
          run-script: 'build-images.sh check-versions.sh'
workflows:
  main:
    jobs:
      - cimg-orb/build-and-deploy