version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: cimg-publishing

jobs:
  build:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          name: "Build Docker Images"
          command: |
            ./check-versions.sh
            ./build-images.sh
            echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
      - deploy:
          name: "Publish Docker Images (main branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              
              echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing cimg/node to Docker Hub production."
                ./push-images.sh
              else
                echo "Skipping publishing."
              fi

              # Update the Docker Hub description
              SONAR_VER=0.15.0
              SONAR_URL="https://github.com/felicianotech/sonar/releases/download/v${SONAR_VER}/sonar-v${SONAR_VER}-linux-amd64.tar.gz"
              mkdir -p $HOME/bin
              curl -sSL $SONAR_URL | tar -xz -C $HOME/bin sonar

              sonar set description cimg/node ./README.md
            fi
